# fly.toml app configuration file generated for unsure-calculator on 2025-04-27T16:34:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unsure-calculator'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
